Analisis de datos
========================================================





```{r directorio}

directorio <- "C:\\Users\\Patatas\\Desktop\\ea1-pr"
setwd(directorio)

```



### Librerias utilizadas
```{r Librerias, results = 'hide'}
paquetes.utilizados <- c("reshape2", "tidyr", "xtable", "knitr", "qdap",
                         "dplyr", "plyr", "lubridate", "ggplot2", "openxlsx")
paquetes.instalados <- rownames(installed.packages())
paquetes.por.instalar <- setdiff(paquetes.utilizados, paquetes.instalados)

# Instala los paquetes faltantes.
if (length(paquetes.por.instalar) != 0 ) install.packages(paquetes.por.instalar, 
                                                          repos = "http://cran.us.r-project.org")
# Carga los paquetes a utilizar.
lapply(paquetes.utilizados, library, character.only = TRUE)
```


```{r  lectura}
setwd("./DATOS/BRUTOS/csv")
nombres <- list.files(pattern= "*.csv")
for (i in 1:length(nombres)){
  assign( substr(nombres[i], 1, nchar(nombres[i])-4), read.csv(nombres[i],stringsAsFactors=FALSE))
}

```

```{r nombres}
nombres_sin <- nombres
for (i in 1:length(nombres)){
  nombres_sin[i] <- substr(nombres[i], 1, nchar(nombres[i])-4)
}

```



```{r melt }

for (i in 1:33){
  assign(nombres_sin[i], melt (data = get(nombres_sin[i]), variable.name ="fuente", value.name= "observaciones", id =1))
  
}



for (i in 34:66){
  assign(nombres_sin[i], melt (data = get(nombres_sin[i]), variable.name ="grupo", value.name= "observaciones", id =1))
  
}

## corregir por incidencia, tasa
for (i in 67:99){
  assign(nombres_sin[i], melt (data = get(nombres_sin[i]), variable.name ="mes", value.name= "observaciones", id =1))
  
}

```






```{r agregar columnas}
## agregar año

for (i in 1:99){
  t <- unlist(nombres_sin[i])
  tdf <- get(unlist(nombres_sin[i])) 
  assign(unlist(nombres_sin[i]), data.frame(tdf, año = as.integer(substr(t,5,8))))
  
}


##agregar genero

for (i in 1:99){
  t <- unlist(nombres_sin[i])
  tdf <- get(unlist(nombres_sin[i])) 
  gen <- substr(t,3,3)
  if(gen == "f"){
    gen_n <- "femenino"
  }else{
    if(gen == "m"){
      gen_n <- "masculino"
    }else{
      if(gen == "g"){
        gen_n <- "general"
      }
    }
  }
  assign(unlist(nombres_sin[i]), data.frame(tdf, genero = gen_n))  
  
}

```



```{r unir en tres tablas}
## por fuente 
fuente <- rbind(get(unlist(nombres_sin[1])),get(unlist(nombres_sin[2])))
for(i in 3:33){
  fuente <- rbind(get(unlist(nombres_sin[i])),fuente)
  
}

## por grupo 
grupo <- rbind(get(unlist(nombres_sin[34])),get(unlist(nombres_sin[35])))
for(i in 36:66){
  grupo <- rbind(get(unlist(nombres_sin[i])),grupo)
  
}

## por mes 
mes <- rbind(get(unlist(nombres_sin[67])),get(unlist(nombres_sin[68])))
for(i in 69:99){
  mes <- rbind(get(unlist(nombres_sin[i])),mes)
  
}
```




```{r limpieza}
###limpieza fuente: nombres de estados repetidos eliminados, reclasificacion de columnas
##numero
estados <- list("Aguascalientes","Baja California","Baja California Sur","Campeche","Coahuila","Colima","Chiapas","Chihuahua","Distrito Federal","Durango","Guanajuato","Guerrero","Hidalgo","Jalisco","México","Michoacán","Morelos","Nayarit","Nuevo León","Oaxaca","Puebla","Querétaro","Quintana Roo","San Luis Potosí","Sinaloa","Sonora","Tabasco","Tamaulipas","Tlaxcala","Veracruz","Yucatán","Zacatecas")

fuente <- within(fuente,{
                         observaciones  <- gsub(" ","", observaciones)
                         observaciones <- as.integer(observaciones)
                         for (i in 1:32){
                           Estado <- gsub(paste0(unlist(estados[i])," "),unlist(estados[i]), Estado)
                           
                         }
                         Estado <- gsub("Baja CaliforniaSur","Baja California Sur",Estado)
                         Estado <- gsub("Baja CaliforniaSu","Baja California Sur",Estado)
                         Estado <- gsub("Baja California Sur ","Baja California Sur",Estado)
                         Estado <- gsub("San Luis Potosi","San Luis Potosí",Estado)
                         Estado <- as.factor(Estado)
                    }
                    )
fuente <- subset (fuente, select= 1:5)##corregir columna agredada (i=32)

## por grupo

grupo <- within(grupo,{
                       Estado <- gsub("Baja California  Sur","Baja California Sur",Estado)
                       Estado <- gsub("San Luis Potosi","San Luis Potosí",Estado)
  
  
  
                    }
                    )



                         

```

